# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

openapi: 3.0.1
info:
  title: Cisco Secure Access Security Feeds API
  version: 1.0.2
  description: |-
    Create and manage the security feeds for the third-party and custom security vendors integrated in Secure Access.
    After you add a security feed, use the Secure Access Destination List API to add domains to the destination list for the security feed.
    Secure Access reviews the each domain in the security feed.
    If Cisco Investigate assigns a **Popularity 90 day** normalized score below **40** for the domain,
    Secure Access adds the domain to the vendor's `thirdparty_block` destination list and blocks the domain.
    The security feed's destination list has the `bundletypeId` of `1`.
  contact:
    name: Cloud Security Developer Community

servers:
  - url: https://api.sse.cisco.com/{basePath}
    variables:
      basePath:
        default: policies/v2

tags:
- name: Feeds
  description: Manage the security feeds for the third-party and custom security vendors.

security:
  - oauthFlow: []

paths:

  /feeds:

    get:
      summary: List Security Feeds
      description: |-
        List the security feeds for the third-party and custom security vendors integrated in Secure Access.
      security:
        - oauthFlow:
          - policies.feeds:read
      operationId: getFeeds
      tags:
        - Feeds
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/feeds'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      summary: Create Security Feed
      description: Create a security feed for a third-party or custom security vendor.
      operationId: createFeed
      tags:
        - Feeds
      requestBody:
        $ref: '#/components/requestBodies/feedCreateRequestBody'
      security:
        - oauthFlow:
          - policies.feeds:write
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/feedObject'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /feeds/{feedId}:

    get:
      summary: Get Security Feed
      description: Get the properties of the security feed for a third-party or custom security vendor.
      operationId: getFeed
      tags:
        - Feeds
      parameters:
        - $ref: '#/components/parameters/feedId'
      security:
        - oauthFlow:
          - policies.feeds:read
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/feedObject'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

    put:
      summary: Update Security Feed
      description: Update the properties of the security feed for a third-party or custom security vendor.
      operationId: updateFeed
      parameters:
        - $ref: '#/components/parameters/feedId'
      tags:
        - Feeds
      requestBody:
        $ref: '#/components/requestBodies/feedPatchRequestBody'
      security:
        - oauthFlow:
          - policies.feeds:write
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/feedObject'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

    delete:
      summary: Delete Security Feed
      description: |-
        Delete the securityfeed for a custom security vendor.
        **Note:** You can not remove a security feed for a third-party security vendor. You can only enable or disable a security feed for a third-party security vendor.
      operationId: deleteFeed
      tags:
        - Feeds
      parameters:
        - $ref: '#/components/parameters/feedId'
      security:
        - oauthFlow:
          - policies.feeds:write
      responses:
        '204':
          description: No Content
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Date:
              $ref: '#/components/headers/Date'
          content: {}
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  securitySchemes:
    oauthFlow:
      type: oauth2
      description: The client credential flow.
      flows:
        clientCredentials:
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
          scopes:
            policies.feeds:write: 'Write policies security security feeds'
            policies.feeds:read: 'Read policies security security feeds'

  headers:
    Content-Type:
      schema:
        type: string
      description: The MIME content type of the response body.
      example: application/json
    Date:
      schema:
        type: string
        pattern: '^[0-90-90-90-9-0-90-9-0-90-9T0-90-9:0-90-9:0-90-9Z]+$'
      description: The timestamp of the response.
      example: '2023-03-14T18:34:25Z'
      #'2023-03-14T18:34:25.412525046Z'

  parameters:
    feedId:
      in: path
      name: feedId
      description: The ID of the security feed.
      required: true
      schema:
        type: integer
      example: 12345

  requestBodies:
    feedCreateRequestBody:
      description: The request body used to create the security feed.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/feedCreate'

    feedPatchRequestBody:
      description: The request body used to update the security feed.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/feedPatch'

  schemas:

    destinationListId:
      type: integer
      description: |-
        The ID of the destination list created for the security feed and security vendor integration.
        The destination list has the `access` type of `thirdparty_block`.
      example: 1234

    organizationId:
      type: integer
      description: The ID of the organization.
      example: 1234567

    feedId:
      type: integer
      example: 123
      description: The ID of the security feed.

    enabled:
      type: string
      description: Specify whether to enable the security feed.
      enum:
        - Y
        - N
      default: N
      example: Y

    feedObject:
      type: object
      description: The properties of the security feed.
      required: [ id, name, organizationId, destinationListId, vendorId, createdAt, modifiedAt ]
      properties:
        id:
          $ref: '#/components/schemas/feedId'
        name:
          $ref: '#/components/schemas/name'
        organizationId:
          $ref: '#/components/schemas/organizationId'
        destinationListId:
          $ref: '#/components/schemas/destinationListId'
        vendorId:
          $ref: '#/components/schemas/vendorId'
        enabled:
          $ref: '#/components/schemas/enabled'
        createdAt:
          type: string
          format: date-time
          description: The date and time when the system created the security feed. The system specifies the timestamp in the ISO 8601 format.
          example: '2024-10-02T20:00:00Z'
        modifiedAt:
          type: string
          format: date-time
          description: The date and time when the system updated the security feed. The system specifies the timestamp in the ISO 8601 format.
          example: '2024-10-02T20:00:00Z'
      example:
        id: 123545
        name: feed one
        organizationId: 146667
        destinationListId: 15666
        vendorId: 11
        enabled: Y
        createdAt: '2024-10-02T20:00:00Z'
        modifiedAt: '2024-10-02T20:00:00Z'

    feeds:
      type: array
      description: The list of security feeds for the integrated custom and third-party security vendors.
      items:
        $ref: '#/components/schemas/feedObject'
      example:
        - id: 123545
          name: feed one
          organizationId: 146667
          destinationListId: 15666
          vendorId: 11
          enabled: Y
          createdAt: '2024-10-02T20:00:00Z'
          modifiedAt: '2024-10-02T20:00:00Z'

    name:
      type: string
      description: The name of the security feed.
      example: feed one

    vendorId:
      type: integer
      default: 0
      description: |-
        The ID of the third-party or custom security vendor.
        The vendor ID for custom security vendors (`0`) is not required to create the security feed.
        | Security Vendor | Feed ID |
        | --------------------------- | -- |
        | Custom Feed | 0 |
        | FireEye | 1 |
        | Cyphort | 3 |
        | ZeroFOX | 5 |
        | ThreatQ | 8 |
        | ThreatConnect | 10 |
        | Cisco AMP Threat Grid | 11 |
      example: 1

    feedCreate:
      type: object
      description: The properties used to create the security feeds for the third-party or custom security vendor.
      required: [name, vendorId]
      properties:
        name:
          $ref: '#/components/schemas/name'
        vendorId:
          $ref: '#/components/schemas/vendorId'
        enabled:
          $ref: '#/components/schemas/enabled'
        apiKey:
          $ref: '#/components/schemas/apiKey'
      example:
        name: feed one
        vendorId: 11
        enabled: Y
        apiKey: 1235asdfjalsdj

    apiKey:
      type: string
      description: The API key for the security feed. The `apiKey` field is optional.
      example: 1235asdfjalsdj

    feedPatch:
      type: object
      description: Update the properties of the security feed.
      required: [name]
      properties:
        name:
          $ref: '#/components/schemas/name'
        enabled:
          $ref: '#/components/schemas/enabled'
        apiKey:
          $ref: '#/components/schemas/apiKey'
      example:
        name: feed two

    BadRequestError:
      type: object
      description: Bad Request
      properties:
        statusCode:
          type: integer
          example: 400
          description: HTTP status error code.
        error:
          type: string
          example: error message
          description: The description of the error.
        message:
          type: string
          example: Bad Request
          description: HTTP status error text.

    UnauthorizedError:
      type: object
      description: Unauthorized
      properties:
        statusCode:
          type: integer
          example: 401
          description: HTTP status error code.
        error:
          type: string
          example: error message
          description: The description of the error.
        message:
          type: string
          example: Unauthorized
          description: HTTP status error text.

    ForbiddenError:
      type: object
      description: Forbidden
      properties:
        statusCode:
          type: integer
          example: 403
          description: HTTP status error code.
        error:
          type: string
          example: error message
          description: The description of the error.
        message:
          type: string
          example: Forbidden
          description: HTTP status error text.

    NotFoundError:
      type: object
      description: Not Found
      properties:
        statusCode:
          type: integer
          example: 404
          description: HTTP status error code.
        error:
          type: string
          example: error message
          description: The description of the error.
        message:
          type: string
          example: Not Found
          description: HTTP status error text.

    ServerError:
      description: Internal Server Error
      type: object
      properties:
        statusCode:
          type: integer
          example: 500
          description: HTTP status error code.
        error:
          type: string
          example: error message
          description: The description of the error.
        message:
          type: string
          example: Internal Server Error
          description: HTTP status error text.

  responses:

    InvalidRequest:
      description: Bad Request
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestError'

    Unauthorized:
      description: Unauthorized
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'

    Forbidden:
      description: Forbidden
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'

    NotFound:
      description: Not Found
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundError'

    ServerError:
      description: Internal Server Error
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Date:
          $ref: '#/components/headers/Date'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerError'
